### ISSUE TITLE
minor documentation bugs

### ISSUE THREAD

**Issue by swsch** [Bogdanp/racket-net-ip#1]
[bytes->ipv6-address](https://docs.racket-lang.org/net-ip/index.html#%28def._%28%28lib._net%2Fip..rkt%29._bytes-~3eipv6-address%29%29) claims to require 4 bytes as input, which seems to be a little short for an ipv6 address.

Both `bytes->ipv*-address` functions claim that an execption is raised if the bytes are not in big-endian order. While the result might not match the expectation of the caller, an exception cannot be raised if the input bytes are not in big-endian order. How about 

    Unpack a byte array in big endian order into an IPv* address. 
    Must be exactly * bytes long, otherwise an exn:fail:contract? is raised.
replacing `*` with the correct number, of course :-)

**Comment by Bogdanp** [comment]
Whoops! Thank you for catching my copy-pasta. :D

**Comment by swsch** [comment]
Couldn't resist due to:

* opportunity for a classic Star Wars reference
* love of pasta, copy or not
* finally a `F!R5T P05T`, now I can retire :-)
