### ISSUE TITLE
Proposal: add a network-last-address function

### ISSUE THREAD

**Issue by aymanosman** [Bogdanp/racket-net-ip#2]
I was pleasantly surprised to find this library when I needed it, so thanks!

I found myself needing to calculate IP ranges from cidr blocks.
I came up with the following:

```
#lang racket

;; LIBRARY

(require net/ip)

(define (network-last-address net)
  (number->ipv4-address
   (+ (sub1 (network-size net))
      (ip-address->number (network-address net)))))

;; APPLICATION

(define (ip-range net)
  (values (ip-address->string (network-address net))
          (ip-address->string (network-last-address net))))

(ip-range (make-network "10.0.0.0/16"))
```

Which got me wondering if it makes sense to expose a `network-last-address` function in this library.

**Comment by Bogdanp** [comment]
I'm happy it helped! I think that would be a good addition so feel free to open a PR.
